name: Windows Executable

on:
  push:
    branches: 
      - "master"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set Home
      run: |
        echo $Env:Home
        echo '::set-env name=HOME::$Env:UserProfile'
    - name: Configure Git
      uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Github Action
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install Python dependencies
      run: |
        pipenv install --dev
    - id: version
      name: Version Files
      run: ./build/version.ps1
    - name: Pushing changed version files
      run: ./build/pushversion.ps1
    - name: Build Executable
      run: |
        pipenv run pyinstaller --workpath ./.pyinstallerbuild --onefile ./build/esnake.spec
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: exe
        path: dist/esnake-${{ steps.version.outputs.new_version }}.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/esnake-${{ steps.version.outputs.new_version }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
