name: Windows Executable

on:
  push:
    branches: 
      - "master"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set Home
      run: |
        echo $Env:Home
        echo "::set-env name=HOME::$Env:UserProfile"
    - name: Configure Git
      uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Github Action
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install Python dependencies
      run: |
        pipenv install --dev
    - id: version
      name: Version Files
      run: ./.github/workflows/version.ps1
    - name: Committing changed files
      run: ./.github/workflows/commitchanges.ps1
    - name: Build Executable
      run: |
        pipenv run pyinstaller --onefile ./src/esnake.spec
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: exe
        path: dist/esnake.exe
    - name: Pushing changed files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifact: "dist/esnake.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.version.outputs.new_version }}
        draft: true